config/routes.rb
Rails.application.routes.draw do
  # Devise routes: use Elabs custom controllers (adds support for username and preferences)
  devise_for :users, path: 'auth', controllers: {
    confirmations: 'auth/confirmations',
    passwords:     'auth/passwords',
    registrations: 'auth/registrations',
    sessions:      'auth/sessions',
    unlocks:       'auth/unlocks',
  }
  # Resources
  resources :albums,    only: [:index, :show], param: :slug do
    resources :uploads, only: [:index]
    post 'comment', to: 'albums#create_comment', as: 'create_comment', param: :slug
  end
  resources :articles,  only: [:index, :show], param: :slug do
    post 'comment', to: 'articles#create_comment', as: 'create_comment', param: :slug
  end
  resources :notes, only: [:index, :show], param: :slug do
    post 'comment', to: 'notes#create_comment', as: 'create_comment', param: :slug
  end
  resources :projects, only: [:index, :show], param: :slug do
    resources :articles, only: [:index]
    resources :albums,   only: [:index]
    resources :notes,    only: [:index]
    resources :uploads,  only: [:index]
    post 'comment', to: 'projects#create_comment', as: 'create_comment', param: :slug
  end
  resources :uploads, only: [:index, :show], param: :slug do
    post 'comment', to: 'uploads#create_comment', as: 'create_comment', param: :slug
  end
  resources :links, only: [:index]

  # Classifiers
  resources :languages, only: [:index, :show], param: :iso639_1 do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :licenses, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :tags, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :users, only: [:index, :show], param: :username do
    resources :albums,   only: [:index]
    resources :links,    only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end

  # Reports
  post '/reports', to: 'reports#create', as: :create_report

  # Activity
  get '/activity', to: 'acts#index', as: :activities

  # Member
  namespace :member do
    resources :albums, except: [:show], param: :slug do
      put 'toggle_publication', to: 'albums#toggle_publication', as: :toggle_publication
    end
    resources :articles, except: [:show], param: :slug do
      put 'toggle_publication', to: 'articles#toggle_publication', as: :toggle_publication
    end
    resources :links, except: [:show] do
      put 'toggle_publication', to: 'links#toggle_publication', as: :toggle_publication
    end
    resources :notes, except: [:show], param: :slug do
      put 'toggle_publication', to: 'notes#toggle_publication', as: :toggle_publication
    end
    resources :projects, except: [:show], param: :slug do
      put 'toggle_publication', to: 'projects#toggle_publication', as: :toggle_publication
    end
    resources :uploads, except: [:show], param: :slug do
      put 'toggle_publication', to: 'uploads#toggle_publication', as: :toggle_publication
    end

    resources :notifications, only: [:index, :destroy]

    resources :comments, only: [:destroy] do
      put '/archive', to: 'comments#archive', as: :archive
    end

    get '/preferences', to: 'preferences#edit', as: :edit_preferences
    put '/preferences', to: 'preferences#update', as: :update_preferences

    get '/infos', to: 'users#edit', as: :edit_infos
    put '/infos', to: 'users#update', as: :update_infos

    post '/markdown_previewer', to: 'markdown_previewer#preview', as: :markdown_preview
  end

  # Admin
  namespace :admin do
    # Content resources
    resources :albums, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'albums#toggle_lock', as: :toggle_lock
    end
    resources :articles, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'articles#toggle_lock', as: :toggle_lock
    end
    resources :links, only: [:index, :destroy] do
      put 'toggle_lock', to: 'links#toggle_lock', as: :toggle_lock
    end
    resources :notes, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'notes#toggle_lock', as: :toggle_lock
    end
    resources :projects, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'projects#toggle_lock', as: :toggle_lock
    end
    resources :uploads, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'uploads#toggle_lock', as: :toggle_lock
    end

    # Basic resources
    resources :announcements, except: [:show]
    resources :languages,     except: [:show], param: :iso639_1
    resources :licenses,      except: [:show], param: :slug
    resources :reports,       only:   [:index, :destroy]
    resources :tags,          except: [:create, :show], param: :slug
    resources :users,         only:   [:index, :show, :destroy], param: :username
  end

  root to: 'home#index'
end

app/models/note.rb
class Note < ApplicationContentRecord
  self.table_name = 'notes'

  SLUGGABLE_FIELD = :created_at
  COUNTER_CACHES = [
    %w[projects notes],
    %w[tags notes],
    'license',
    'language',
    'user',
  ].freeze

  validates :content, presence: true
  validates :slug,    presence: true, uniqueness: true
  validates_with AssociatedAuthorValidator, relations: %w[project]

  belongs_to :user
  belongs_to :license
  belongs_to :language
  has_many :notes_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :projects_notes # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :tags,     through: :notes_tags,     dependent: :destroy
  has_many :projects, through: :projects_notes, dependent: :destroy
  has_many :comments, as: 'content', dependent: :destroy
  # Public filters
  has_many :public_projects, -> { publicly_visible }, through: :projects_notes, source: :project

  def title_to_display
    I18n.t('activerecord.attributes.note.title', date: I18n.l(created_at, format: :medium))
  end

  def short_text_to_display
    content
  end

  def long_text_to_display
    nil
  end
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < AdminContentApplicationController
    DEFAULT_ORDER_FIELD = 'content'.freeze
    MODEL               = Note
    PLURAL_NAME         = 'notes'.freeze
    SINGULAR_NAME       = 'note'.freeze
  end
end

app/controllers/member/notes_controller.rb
module Member
  class NotesController < MemberContentApplicationController
    ALLOWED_FIELDS    = [:content, :sfw, :hidden_in_history, :published, :license_id, :language_id, :tags_list, :minor_update, :update_description].freeze
    ALLOWED_RELATIONS = { project_ids: [] }.freeze
    MODEL             = Note
    PLURAL_NAME       = 'notes'.freeze
    SINGULAR_NAME     = 'note'.freeze
  end
end

app/controllers/notes_controller.rb
class NotesController < ContentApplicationController
  ALLOWED_NESTED_FROM = %w[language license tag user project].freeze
  ALLOWED_ORDER_FROM  = %w[published_at updated_at].freeze

  before_action :set_note, only: [:show]

  # GET /notes
  # GET /notes.json
  def index
    @notes = scope_request(Note.published).page(params[:page]).per(self.class::MAX_ITEMS_PER_PAGE)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find_publicly_visible(params[:slug])
  end
end

app/views/notes/_filters.html.haml
.page__header__actions__filters
  .page__header__actions__filters__group
    .page__header__actions__filters__group__title= t('.sort_by')
    = order_link t('.pub_date'), 'published_at'
    = order_link t('.upd_date'), 'updated_at'

  .page__header__actions__filters__group
    .page__header__actions__filters__group__title= t('.nsfw_content')
    = sfw_status_links

app/views/notes/_note_inline.haml
- if !show_item? note
  = render 'layouts/hidden_entry_inline', entity: note
- else
  %span.note.note--inline
    = icon 'note'
    = link_to t('.note_id', id: note.id), note
    - if note.language.iso639_1 != locale
      (#{note.language.iso639_1})

app/views/notes/index.html.haml
- @page_title = t('.notes')

.notes-list
  = render 'layouts/empty' if @notes.length.zero?

  - @notes.each do |n|
    = render 'layouts/content_card', entity: n

= paginate @notes

app/views/notes/show.html.haml
- if !show_item? @note
  - @page_title = t('.content_not_displayed')
  = render 'layouts/hidden_entry_full', entity: @note
- else
  - @page_title = t('.a_note')
  .note.note--full
    %aside.details
      = render 'layouts/content_full_details', entity: @note

    .content
      %article{ lang: @note.language.iso639_1 }
        = render_entity_content @note, :content

  = render 'comments/comments',
            entity: @note,
            new_comment: @new_comment,
            url: note_create_comment_path(@note)

app/views/notes/show.md.erb
<%
title            = t('.title', type: t('.note'), title: @note.published_at)
username         = @note.user.display_name
publication_date = @note.published_at
has_update       = @note.published_at < @note.updated_at

if params[:md_format] == 'pandoc' %>
% <%= title %>
% <%= username %>
% <%= publication_date %>

<% else %>
# <%= title %>

- **<%= t('.author') %>** <%= username %>
- **<%= t('.published_at') %>** <%= publication_date %>
<% end %>
<% if has_update %>
- **<%= t('.updated_at') %>** <%= @note.updated_at %>
<% end %>
- **<%= t('.language') %>** <%= @note.language.name %>
- **<%= t('.license') %>** [<%= @note.license.name %>](<%= @note.license.url %>)
- **<%= t('.projects') %>**
<% @note.projects.each do |project| %>
  - [<%= project.name %>](<%= project_url(project) %>)
<% end %>
- **<%= t('.tags') %>** <% @note.tags.each do |tag| %><%= tag.name %>, <% end %>
- **<%= t('.original_url') %>** <%= note_url(@note) %>
- **<%= t('.sfw') %>** <%= @note.sfw ? t('yes') : t('no') %>

---

<%= @note.content %>