config/routes.rb
Rails.application.routes.draw do
  # Devise routes: use Elabs custom controllers (adds support for username and preferences)
  devise_for :users, path: 'auth', controllers: {
    confirmations: 'auth/confirmations',
    passwords:     'auth/passwords',
    registrations: 'auth/registrations',
    sessions:      'auth/sessions',
    unlocks:       'auth/unlocks',
  }
  # Resources
  resources :albums,    only: [:index, :show], param: :slug do
    resources :uploads, only: [:index]
    post 'comment', to: 'albums#create_comment', as: 'create_comment', param: :slug
  end
  resources :articles,  only: [:index, :show], param: :slug do
    post 'comment', to: 'articles#create_comment', as: 'create_comment', param: :slug
  end
  resources :notes, only: [:index, :show], param: :slug do
    post 'comment', to: 'notes#create_comment', as: 'create_comment', param: :slug
  end
  resources :projects, only: [:index, :show], param: :slug do
    resources :articles, only: [:index]
    resources :albums,   only: [:index]
    resources :notes,    only: [:index]
    resources :uploads,  only: [:index]
    post 'comment', to: 'projects#create_comment', as: 'create_comment', param: :slug
  end
  resources :uploads, only: [:index, :show], param: :slug do
    post 'comment', to: 'uploads#create_comment', as: 'create_comment', param: :slug
  end
  resources :links, only: [:index]

  # Classifiers
  resources :languages, only: [:index, :show], param: :iso639_1 do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :licenses, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :tags, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :users, only: [:index, :show], param: :username do
    resources :albums,   only: [:index]
    resources :links,    only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end

  # Reports
  post '/reports', to: 'reports#create', as: :create_report

  # Activity
  get '/activity', to: 'acts#index', as: :activities

  # Member
  namespace :member do
    resources :albums, except: [:show], param: :slug do
      put 'toggle_publication', to: 'albums#toggle_publication', as: :toggle_publication
    end
    resources :articles, except: [:show], param: :slug do
      put 'toggle_publication', to: 'articles#toggle_publication', as: :toggle_publication
    end
    resources :links, except: [:show] do
      put 'toggle_publication', to: 'links#toggle_publication', as: :toggle_publication
    end
    resources :notes, except: [:show], param: :slug do
      put 'toggle_publication', to: 'notes#toggle_publication', as: :toggle_publication
    end
    resources :projects, except: [:show], param: :slug do
      put 'toggle_publication', to: 'projects#toggle_publication', as: :toggle_publication
    end
    resources :uploads, except: [:show], param: :slug do
      put 'toggle_publication', to: 'uploads#toggle_publication', as: :toggle_publication
    end

    resources :notifications, only: [:index, :destroy]

    resources :comments, only: [:destroy] do
      put '/archive', to: 'comments#archive', as: :archive
    end

    get '/preferences', to: 'preferences#edit', as: :edit_preferences
    put '/preferences', to: 'preferences#update', as: :update_preferences

    get '/infos', to: 'users#edit', as: :edit_infos
    put '/infos', to: 'users#update', as: :update_infos

    post '/markdown_previewer', to: 'markdown_previewer#preview', as: :markdown_preview
  end

  # Admin
  namespace :admin do
    # Content resources
    resources :albums, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'albums#toggle_lock', as: :toggle_lock
    end
    resources :articles, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'articles#toggle_lock', as: :toggle_lock
    end
    resources :links, only: [:index, :destroy] do
      put 'toggle_lock', to: 'links#toggle_lock', as: :toggle_lock
    end
    resources :notes, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'notes#toggle_lock', as: :toggle_lock
    end
    resources :projects, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'projects#toggle_lock', as: :toggle_lock
    end
    resources :uploads, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'uploads#toggle_lock', as: :toggle_lock
    end

    # Basic resources
    resources :announcements, except: [:show]
    resources :languages,     except: [:show], param: :iso639_1
    resources :licenses,      except: [:show], param: :slug
    resources :reports,       only:   [:index, :destroy]
    resources :tags,          except: [:create, :show], param: :slug
    resources :users,         only:   [:index, :show, :destroy], param: :username
  end

  root to: 'home#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  self.table_name = 'tags'
  include Sluggable

  SLUGGABLE_FIELD = :name
  SLUG_FIELD      = :slug

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true

  has_many :albums_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :articles_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :links_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :notes_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :projects_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :uploads_tags # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :albums,   through: :albums_tags,     dependent: :destroy
  has_many :articles, through: :articles_tags,   dependent: :destroy
  has_many :links,    through: :links_tags,      dependent: :destroy
  has_many :notes,    through: :notes_tags,      dependent: :destroy
  has_many :projects, through: :projects_tags,   dependent: :destroy
  has_many :uploads,  through: :uploads_tags,    dependent: :destroy
  # Public filters
  has_many :public_albums,   -> { publicly_visible }, through: :albums_tags,   source: :album
  has_many :public_articles, -> { publicly_visible }, through: :articles_tags, source: :article
  has_many :public_links,    -> { publicly_visible }, through: :links_tags,    source: :link
  has_many :public_notes,    -> { publicly_visible }, through: :notes_tags,    source: :note
  has_many :public_projects, -> { publicly_visible }, through: :projects_tags, source: :project
  has_many :public_uploads,  -> { publicly_visible }, through: :uploads_tags,  source: :upload
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < AdminApplicationController
    DEFAULT_ORDER_FIELD = 'name'.freeze

    before_action :set_tag, only: [:edit, :update, :destroy]

    # GET /tags
    # GET /tags.json
    def index
      order     = params['order_by'] || self.class::DEFAULT_ORDER_FIELD
      direction = params['direction'] || 'desc'
      @tags     = Tag.order(order => direction).all
    end

    # GET /tags/1/edit
    def edit; end

    # PATCH/PUT /tags/1
    # PATCH/PUT /tags/1.json
    def update
      respond_to do |format|
        if @tag.update(tag_params)
          format.html { redirect_to admin_tags_url, notice: t('.update_success') }
          format.json { render :_tag, status: :ok, location: admin_tags_url, locals: { tag: @tag } }
        else
          format.html { render :edit, tag: @tag }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /tags/1
    # DELETE /tags/1.json
    def destroy
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to admin_tags_url, notice: t('.destroy_success') }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find_by!(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < PublicController
  ALLOWED_ORDER_FROM = %w[name].freeze
  DEFAULT_ORDER      = { name: :desc }.freeze

  before_action :set_tag, only: [:show]

  # GET /tags
  # GET /tags.json
  def index
    @tags = scope_request Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find_by!(slug: params[:slug])
  end
end

app/views/tags/_filters.html.haml
.page__header__actions__filters
  .page__header__actions__filters__group
    .page__header__actions__filters__group__title= t('.sort_by')
    = order_link t('.name'), 'name'

app/views/tags/index.html.haml
- @page_title = t('.tags_list')

= render 'layouts/empty' if @tags.length.zero?

.tags-list
  - @tags.each do |tag|
    .tag.tag-card
      %header
        .icon= icon 'tag', ['2x']
        .headers
          %h3.title= link_to tag.name, tag

      .content
        = link_to tag_projects_path(tag), class: 'btn btn--block' do
          = icon 'project', ['icon']
          .text= t('generic.counts.projects', count: tag.projects_count)
        = link_to tag_articles_path(tag), class: 'btn btn--block' do
          = icon 'article', ['icon']
          .text= t('generic.counts.articles', count: tag.articles_count)
        = link_to tag_notes_path(tag), class: 'btn btn--block' do
          = icon 'note', ['icon']
          .text= t('generic.counts.notes', count: tag.notes_count)
        = link_to tag_uploads_path(tag), class: 'btn btn--block' do
          = icon 'image', ['icon']
          .text= t('generic.counts.uploads', count: tag.uploads_count)
        = link_to tag_albums_path(tag), class: 'btn btn--block' do
          = icon 'album', ['icon']
          .text= t('generic.counts.albums', count: tag.albums_count)
        = link_to tag_links_path(tag), class: 'btn btn--block' do
          = icon 'link', ['icon']
          .text= t('generic.counts.links', count: tag.links_count)

app/views/tags/show.html.haml
- @page_title = @tag.name

.tag.tag--full
  %aside.details.always--inline
    %ul
      %li.separator
        %ul
          %li.detail
            = icon 'amount'
            %strong= t('.albums_count')
            = @tag.albums_count
          %li.detail
            = icon 'amount'
            %strong= t('.articles_count')
            = @tag.articles_count
          %li.detail
            = icon 'amount'
            %strong= t('.notes_count')
            = @tag.notes_count
          %li.detail
            = icon 'amount'
            %strong= t('.projects_count')
            = @tag.projects_count
          %li.detail
            = icon 'amount'
            %strong= t('.uploads_count')
            = @tag.uploads_count
          %li.detail
            = icon 'amount'
            %strong= t('.links_count')
            = @tag.links_count


  .content
    = render 'layouts/content_associations', is_section: true, entity: @tag