config/routes.rb
Rails.application.routes.draw do
  # Devise routes: use Elabs custom controllers (adds support for username and preferences)
  devise_for :users, path: 'auth', controllers: {
    confirmations: 'auth/confirmations',
    passwords:     'auth/passwords',
    registrations: 'auth/registrations',
    sessions:      'auth/sessions',
    unlocks:       'auth/unlocks',
  }
  # Resources
  resources :albums,    only: [:index, :show], param: :slug do
    resources :uploads, only: [:index]
    post 'comment', to: 'albums#create_comment', as: 'create_comment', param: :slug
  end
  resources :articles,  only: [:index, :show], param: :slug do
    post 'comment', to: 'articles#create_comment', as: 'create_comment', param: :slug
  end
  resources :notes, only: [:index, :show], param: :slug do
    post 'comment', to: 'notes#create_comment', as: 'create_comment', param: :slug
  end
  resources :projects, only: [:index, :show], param: :slug do
    resources :articles, only: [:index]
    resources :albums,   only: [:index]
    resources :notes,    only: [:index]
    resources :uploads,  only: [:index]
    post 'comment', to: 'projects#create_comment', as: 'create_comment', param: :slug
  end
  resources :uploads, only: [:index, :show], param: :slug do
    post 'comment', to: 'uploads#create_comment', as: 'create_comment', param: :slug
  end
  resources :links, only: [:index]

  # Classifiers
  resources :languages, only: [:index, :show], param: :iso639_1 do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :licenses, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :tags, only: [:index, :show], param: :slug do
    resources :albums,   only: [:index]
    resources :articles, only: [:index]
    resources :links,    only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end
  resources :users, only: [:index, :show], param: :username do
    resources :albums,   only: [:index]
    resources :links,    only: [:index]
    resources :articles, only: [:index]
    resources :notes,    only: [:index]
    resources :projects, only: [:index]
    resources :uploads,  only: [:index]
  end

  # Reports
  post '/reports', to: 'reports#create', as: :create_report

  # Activity
  get '/activity', to: 'acts#index', as: :activities

  # Member
  namespace :member do
    resources :albums, except: [:show], param: :slug do
      put 'toggle_publication', to: 'albums#toggle_publication', as: :toggle_publication
    end
    resources :articles, except: [:show], param: :slug do
      put 'toggle_publication', to: 'articles#toggle_publication', as: :toggle_publication
    end
    resources :links, except: [:show] do
      put 'toggle_publication', to: 'links#toggle_publication', as: :toggle_publication
    end
    resources :notes, except: [:show], param: :slug do
      put 'toggle_publication', to: 'notes#toggle_publication', as: :toggle_publication
    end
    resources :projects, except: [:show], param: :slug do
      put 'toggle_publication', to: 'projects#toggle_publication', as: :toggle_publication
    end
    resources :uploads, except: [:show], param: :slug do
      put 'toggle_publication', to: 'uploads#toggle_publication', as: :toggle_publication
    end

    resources :notifications, only: [:index, :destroy]

    resources :comments, only: [:destroy] do
      put '/archive', to: 'comments#archive', as: :archive
    end

    get '/preferences', to: 'preferences#edit', as: :edit_preferences
    put '/preferences', to: 'preferences#update', as: :update_preferences

    get '/infos', to: 'users#edit', as: :edit_infos
    put '/infos', to: 'users#update', as: :update_infos

    post '/markdown_previewer', to: 'markdown_previewer#preview', as: :markdown_preview
  end

  # Admin
  namespace :admin do
    # Content resources
    resources :albums, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'albums#toggle_lock', as: :toggle_lock
    end
    resources :articles, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'articles#toggle_lock', as: :toggle_lock
    end
    resources :links, only: [:index, :destroy] do
      put 'toggle_lock', to: 'links#toggle_lock', as: :toggle_lock
    end
    resources :notes, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'notes#toggle_lock', as: :toggle_lock
    end
    resources :projects, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'projects#toggle_lock', as: :toggle_lock
    end
    resources :uploads, only: [:index, :destroy], param: :slug do
      put 'toggle_lock', to: 'uploads#toggle_lock', as: :toggle_lock
    end

    # Basic resources
    resources :announcements, except: [:show]
    resources :languages,     except: [:show], param: :iso639_1
    resources :licenses,      except: [:show], param: :slug
    resources :reports,       only:   [:index, :destroy]
    resources :tags,          except: [:create, :show], param: :slug
    resources :users,         only:   [:index, :show, :destroy], param: :username
  end

  root to: 'home#index'
end

app/controllers/admin/licenses_controller.rb
module Admin
  class LicensesController < AdminApplicationController
    DEFAULT_ORDER_FIELD = 'name'.freeze

    before_action :set_license, only: [:edit, :update, :destroy]

    # GET /licenses
    # GET /licenses.json
    def index
      order     = params['order_by'] || self.class::DEFAULT_ORDER_FIELD
      direction = params['direction'] || 'desc'
      @licenses = License.order(order => direction).all
    end

    # GET /licenses/new
    def new
      @license = License.new
    end

    # GET /licenses/1/edit
    def edit; end

    # POST /licenses
    # POST /licenses.json
    def create
      @license = License.new(license_params)

      respond_to do |format|
        if @license.save
          format.html { redirect_to admin_licenses_url, notice: t('.create_success') }
          format.json { render '_license', status: :created, location: @license, locals: { license: @license } }
        else
          format.html { render :new }
          format.json { render json: @license.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /licenses/1
    # PATCH/PUT /licenses/1.json
    def update
      respond_to do |format|
        if @license.update(license_params)
          format.html { redirect_to admin_licenses_url, notice: t('.update_success') }
          format.json { render '_license', status: :ok, location: @license, locals: { license: @license } }
        else
          format.html { render :edit }
          format.json { render json: @license.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /licenses/1
    # DELETE /licenses/1.json
    def destroy
      @license.destroy
      respond_to do |format|
        format.html { redirect_to admin_licenses_url, notice: t('.destroy_success') }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = License.find_by!(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_params
      params.require(:license).permit(:name, :url, :tldr_url, :icon)
    end
  end
end

app/controllers/licenses_controller.rb
class LicensesController < PublicController
  ALLOWED_ORDER_FROM = %w[name].freeze
  DEFAULT_ORDER      = { name: :asc }.freeze

  before_action :set_license, only: [:show]

  # GET /licenses
  # GET /licenses.json
  def index
    @licenses = scope_request License.all
  end

  # GET /licenses/1
  # GET /licenses/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_license
    @license = License.find_by!(slug: params[:slug])
  end
end

app/views/admin/licenses/_form.html.haml
= form_for license, url: license.id ? admin_license_path : admin_licenses_path do |f|
  - if license.errors.any?
    .error
      %h2= t('.save_error', count: license.errors.count)
      %ul
        - license.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    .field-input= f.text_field :name
  .field
    = f.label :url
    .field-input= f.text_field :url
  .field
    = f.label :tldr_url
    .field-input= f.text_field :tldr_url
  .field
    = f.label :icon
    .field-input= f.text_field :icon

  .actions
    .actions-buttons
      = f.submit t('.save'), class: 'btn btn--save'

app/views/admin/licenses/edit.html.haml
- @page_title = t('.editing_license')

.page__actions
  = link_to t('.view_online'), @license, class: 'btn btn--show'

= render 'form', license: @license

app/views/admin/licenses/index.html.haml
- @page_title = t('.licenses')

.page__actions
  = link_to t('.new_license'), new_admin_license_path, class: 'btn btn--new'

%table.licenses-list
  %thead
    %tr
      %th= admin_order_by_link t('.name'), 'name'
      %th= admin_order_by_link t('.url'), 'url'
      %th= admin_order_by_link t('.tl_dr_url'), 'tldr_url'
      %th= admin_order_by_link t('.icon'), 'icon'
      %th= admin_order_by_link t('.albums'), 'albums_count'
      %th= admin_order_by_link t('.articles'), 'articles_count'
      %th= admin_order_by_link t('.notes'), 'notes_count'
      %th= admin_order_by_link t('.projects'), 'projects_count'
      %th= admin_order_by_link t('.uploads'), 'uploads_count'
      %th

  %tbody
    - @licenses.each do |license|
      %tr.license
        %td= license.name
        %td.is-icon
          = link_to license.url, target: '_blank', rel: 'noopener noreferrer' do
            = icon 'home'
        %td.is-icon
          = link_to license.tldr_url, target: '_blank', rel: 'noopener noreferrer' do
            = icon 'cut'
        %td
          = license_icon license
          = license.icon
        %td.is-counter= license.albums_count
        %td.is-counter= license.articles_count
        %td.is-counter= license.notes_count
        %td.is-counter= license.projects_count
        %td.is-counter= license.uploads_count
        %td.actions
          .btn-group
            = show_online_link license
            = admin_edit_link 'license', license
            = admin_destroy_link 'license', license

app/views/admin/licenses/new.html.haml
- @page_title = t('.new_license')

= render 'form', license: @license